apiVersion: v1
kind: Service
metadata:
  name: svelte-standalone
  namespace: svelte-standalone
  labels:
    app: svelte-standalone
spec:
  type: ClusterIP
  selector:
    app: svelte-standalone
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
